
package server;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SoapServer", targetNamespace = "http://server/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SoapServer {


    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getContent", targetNamespace = "http://server/", className = "server.GetContent")
    @ResponseWrapper(localName = "getContentResponse", targetNamespace = "http://server/", className = "server.GetContentResponse")
    @Action(input = "http://server/SoapServer/getContentRequest", output = "http://server/SoapServer/getContentResponse")
    public List<String> getContent();

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getColumns", targetNamespace = "http://server/", className = "server.GetColumns")
    @ResponseWrapper(localName = "getColumnsResponse", targetNamespace = "http://server/", className = "server.GetColumnsResponse")
    @Action(input = "http://server/SoapServer/getColumnsRequest", output = "http://server/SoapServer/getColumnsResponse")
    public int getColumns();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "deleteContent", targetNamespace = "http://server/", className = "server.DeleteContent")
    @ResponseWrapper(localName = "deleteContentResponse", targetNamespace = "http://server/", className = "server.DeleteContentResponse")
    @Action(input = "http://server/SoapServer/deleteContentRequest", output = "http://server/SoapServer/deleteContentResponse")
    public void deleteContent(
        @WebParam(name = "arg0", targetNamespace = "")
        List<String> arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "addContent", targetNamespace = "http://server/", className = "server.AddContent")
    @ResponseWrapper(localName = "addContentResponse", targetNamespace = "http://server/", className = "server.AddContentResponse")
    @Action(input = "http://server/SoapServer/addContentRequest", output = "http://server/SoapServer/addContentResponse")
    public void addContent(
        @WebParam(name = "arg0", targetNamespace = "")
        List<String> arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "changeContent", targetNamespace = "http://server/", className = "server.ChangeContent")
    @ResponseWrapper(localName = "changeContentResponse", targetNamespace = "http://server/", className = "server.ChangeContentResponse")
    @Action(input = "http://server/SoapServer/changeContentRequest", output = "http://server/SoapServer/changeContentResponse")
    public void changeContent(
        @WebParam(name = "arg0", targetNamespace = "")
        List<String> arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        List<String> arg1);

}
